spring:
  application:
    name: cloud-pay-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cheng.pay.model
  configuration:
    map-underscore-to-camel-case: true